import Footer from "@/components/footer";
import Header from "@/components/header";
import { OfferProvider } from "@/contexts/offer-context";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Box } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <OfferProvider>
          <Header />
          <Box sx={{ minHeight: "calc(100vh - 120px)" }}>{children}</Box>
          <Footer />
        </OfferProvider>
      </body>
    </html>
  );
}
